"""
Synthetic credit card fraud data generator.
Mimics the industry-standard ULB credit card dataset schema
(Time, V1..V28, Amount, Class), while being fully generated by code so the
repository can run immediately after cloning without external data downloads.

Design choices, intentionally close to real fraud data:
- Extreme class imbalance: fraud is roughly 0.3%.
- 28 anonymized V1..V28 features, similar to PCA-transformed features. A small
  subset carries real fraud signal and the rest are noise, matching the shape of
  many production risk datasets.
- Amount is right-skewed (lognormal), with a slightly different fraud profile.
"""
import numpy as np
import pandas as pd
import argparse, os

def generate(n=284807, fraud_rate=0.0030, seed=42):
    rng = np.random.default_rng(seed)
    n_fraud = int(n * fraud_rate)
    n_legit = n - n_fraud

    def make_features(n_rows, signal_shift):
        # 28 features: the first 6 carry signal; the remaining 22 are noise.
        X = rng.standard_normal((n_rows, 28))
        signal_cols = [0, 1, 2, 3, 9, 13]   # mimic a few strong features
        for j, s in zip(signal_cols, signal_shift):
            X[:, j] += s
        return X

    # Legitimate transactions are centered; fraud is shifted but still overlaps.
    X_legit = make_features(n_legit, [0, 0, 0, 0, 0, 0])
    X_fraud = make_features(n_fraud, [-2.1, 1.8, -1.5, 1.2, -1.0, 1.4])

    X = np.vstack([X_legit, X_fraud])
    y = np.r_[np.zeros(n_legit, dtype=int), np.ones(n_fraud, dtype=int)]

    # Amount is right-skewed; fraud has a slightly different distribution.
    amt_legit = np.round(rng.lognormal(3.0, 1.1, n_legit) + 1, 2)
    amt_fraud = np.round(rng.lognormal(3.4, 1.3, n_fraud) + 1, 2)
    amount = np.r_[amt_legit, amt_fraud]

    # Time is seconds over two days, matching ULB; fraud is slightly night-heavy.
    t_legit = rng.uniform(0, 172792, n_legit)
    t_fraud = rng.uniform(0, 172792, n_fraud)
    night = rng.random(n_fraud) < 0.35
    t_fraud[night] = (t_fraud[night] % 86400) * 0.25  # bias toward early morning
    time = np.r_[t_legit, t_fraud]

    cols = {f"V{i+1}": X[:, i] for i in range(28)}
    df = pd.DataFrame(cols)
    df.insert(0, "Time", np.round(time).astype(int))
    df["Amount"] = amount
    df["Class"] = y

    # Shuffle rows.
    df = df.sample(frac=1, random_state=seed).reset_index(drop=True)
    return df

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=284807)
    ap.add_argument("--out", default="data/creditcard_synthetic.csv")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    df = generate(n=args.n, seed=args.seed)
    df.to_csv(args.out, index=False)
    print(f"Generated {len(df):,} transactions -> {args.out}")
    print(f"Fraud rate: {df.Class.mean()*100:.3f}%  (fraud {int(df.Class.sum()):,})")
